package jp.covid19_kagawa.covid19information

enum class Prefecture(val prefCode: Int) {
    HOKKAIDO(1) { override fun prefecturePageLink(): String = "https://stopcovid19.hokkaido.dev/" },
    AOMORI(2){ override fun prefecturePageLink(): String = "https://covid19.codeforaomori.org/" },
    IWATE(3){ override fun prefecturePageLink(): String = "https://iwate.stopcovid19.jp/" },
    MIYAGI(4){ override fun prefecturePageLink(): String = "https://miyagi.stopcovid19.jp/" },
    AKITA(5){ override fun prefecturePageLink(): String = "" },
    YAMAGATA(6){ override fun prefecturePageLink(): String = "" },
    FUKUSHIMA(7){ override fun prefecturePageLink(): String = "https://fukushima-covid19.firebaseapp.com/" },
    IBARAKI(8){ override fun prefecturePageLink(): String = "https://covid19-ibaraki.netlify.com/" },
    TOCHIGI(9){ override fun prefecturePageLink(): String = "" },
    GUMMA(10){ override fun prefecturePageLink(): String = "https://stopcovid19-gunma.netlify.com/" },
    SAITAMA(11){ override fun prefecturePageLink(): String = "" },
    CHIBA(12){ override fun prefecturePageLink(): String = "https://stopcovid19.code4chiba.org/" },
    TOKYO(13){ override fun prefecturePageLink(): String = "https://stopcovid19.metro.tokyo.lg.jp/" },
    KANAGAWA(14){ override fun prefecturePageLink(): String = "" },
    NIIGATA(15){ override fun prefecturePageLink(): String = "" },
    TOYAMA(16){ override fun prefecturePageLink(): String = "" },
    ISHIKAWA(17){ override fun prefecturePageLink(): String = "" },
    FUKUI(18){ override fun prefecturePageLink(): String = "" },
    YAMANASHI(19){ override fun prefecturePageLink(): String = "" },
    NAGANO(20){ override fun prefecturePageLink(): String = "" },
    GIFU(21){ override fun prefecturePageLink(): String = "" },
    SHIZUOKA(22){ override fun prefecturePageLink(): String = "" },
    AICHI(23){ override fun prefecturePageLink(): String = "" },
    MIE(24){ override fun prefecturePageLink(): String = "" },
    SHIGA(25){ override fun prefecturePageLink(): String = "" },
    KYOTO(26){ override fun prefecturePageLink(): String = "" },
    OSAKA(27){ override fun prefecturePageLink(): String = "" },
    HYOGO(28){ override fun prefecturePageLink(): String = "" },
    NARA(29){ override fun prefecturePageLink(): String = "" },
    WAKAYAMA(30){ override fun prefecturePageLink(): String = "" },
    TOTTORI(31){ override fun prefecturePageLink(): String = "" },
    SHIMANE(32){ override fun prefecturePageLink(): String = "" },
    OKAYAMA(33){ override fun prefecturePageLink(): String = "" },
    HIROSHIMA(34){ override fun prefecturePageLink(): String = "" },
    YAMAGUCHI(35){ override fun prefecturePageLink(): String = "" },
    TOKUSHIMA(36){ override fun prefecturePageLink(): String = "" },
    KAGAWA(37){ override fun prefecturePageLink(): String = "https://covid19-kagawa.jp/" },
    EHIME(38){ override fun prefecturePageLink(): String = "" },
    KOCHI(39){ override fun prefecturePageLink(): String = "" },
    FUKUOKA(40){ override fun prefecturePageLink(): String = "" },
    SAGA(41){ override fun prefecturePageLink(): String = "" },
    NAGASAKI(42){ override fun prefecturePageLink(): String = "" },
    KUMAMOTO(43){ override fun prefecturePageLink(): String = "" },
    OITA(44){ override fun prefecturePageLink(): String = "" },
    MIYAZAKI(45){ override fun prefecturePageLink(): String = "" },
    KAGOSHIMA(46){ override fun prefecturePageLink(): String = "" },
    OKINAWA(47){ override fun prefecturePageLink(): String = "" },
    DEFAULT(0){ override fun prefecturePageLink(): String = "" };

    abstract fun prefecturePageLink(): String

}